### ISSUE TITLE
Abot the firebase and dialogflow

### ISSUE THREAD

**Issue by Durgasish1o** [muhrahmatullah/android-chatbot#5]
sir 
i am really a big fan of yours ,please help me out in this trouble i just want to connect my dialogflow in your project after cloning it please sir help me out i am in urgent need just can i contact you on whattsapp even gmail will be fine just sir a little help and i wont make you trouble after that

**Comment by muhrahmatullah** [comment]
Hi @Durgasish1o ,
Thanks for the words, in order to connect it with your own dialogflow project, you need to use your own google-service.json file from your own firebase project also you need to use your own dialogflow agent id, you can change the id on MainActivity.kt on line 86 on (AIConfiguration).

**Comment by Durgasish1o** [comment]
Sir will changing the dialogflow agent id on MainActivity file will work after I creat my own account without changing the firebase id if not please guide me how can i do that in fire base and what all id i need to change in the project please sir i will be greatful to you

**Comment by muhrahmatullah** [comment]
it will work but, I suggest you use your own firebase project because the repo is tailored with my project and I can revoke it at any given time hence your project will not be able to work. to create a firebase project, you can start from this : https://firebase.google.com/docs/android/setup

**Comment by Durgasish1o** [comment]
Thank u sir but how to I connect it to ibm Watson and the line 86 it's the Clint id i also need to make changes to the res package containing the values how can i do that one more question sir without using fire base can i only use ibm and train it

**Comment by muhrahmatullah** [comment]
Maybe you can start to read the docs for ibm watson integration since I myself haven't use that.

**Comment by Durgasish1o** [comment]
Sir i have added my project to firebasedata base and dialogflow with data base but in the logcat window it is showing that permission denied and showing error connecting to database sir can you please tell me how to connect to dialogflow with firebase this process I want to know please you don't need to explain in details just write the hints what you did and I can make it please sir beg you

**Comment by muhrahmatullah** [comment]
have you imported the appropriate google-service.json file? what is the error says? please attach the log so I can help debug

**Comment by Durgasish1o** [comment]
`2020-04-28 21:41:57.784 2772-2772/com.durga.hipe W/FirebaseRecyclerAdapter: com.google.firebase.database.DatabaseException: Firebase Database error: Permission denied
        at com.google.firebase.database.DatabaseError.toException(com.google.firebase:firebase-database@@19.3.0:229)
        at com.firebase.ui.database.FirebaseRecyclerAdapter.onError(FirebaseRecyclerAdapter.java:97)
        at com.firebase.ui.database.FirebaseRecyclerAdapter.onError(FirebaseRecyclerAdapter.java:28)
        at com.firebase.ui.common.BaseObservableSnapshotArray.notifyOnError(BaseObservableSnapshotArray.java:194)
        at com.firebase.ui.database.FirebaseArray.onCancelled(FirebaseArray.java:110)
        at com.google.firebase.database.core.ValueEventRegistration.fireCancelEvent(com.google.firebase:firebase-database@@19.3.0:80)
        at com.google.firebase.database.core.view.CancelEvent.fire(com.google.firebase:firebase-database@@19.3.0:40)
        at com.google.firebase.database.core.view.EventRaiser$1.run(com.google.firebase:firebase-database@@19.3.0:55)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2020-04-28 21:42:03.287 2772-2848/com.durga.hipe V/FA: Inactivity, disconnecting from the service
2020-04-28 21:42:33.082 2772-2772/com.durga.hipe I/AssistStructure: Flattened final assist data: 2200 bytes, containing 1 windows, 8 views
2020-04-28 21:42:43.859 2772-3438/com.durga.hipe W/com.durga.hipe: Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (light greylist, reflection)
2020-04-28 21:42:44.182 2772-2863/com.durga.hipe W/RepoOperation: setValue at /chat/-M60YxhIall50WyyoHzf failed: DatabaseError: Permission denied
2020-04-28 21:42:47.139 2772-2863/com.durga.hipe W/RepoOperation: setValue at /chat/-M60YyOQJwAZ6raidSEE failed: DatabaseError: Permission denied
`

**Comment by Durgasish1o** [comment]
![2020-04-28](https://user-images.githubusercontent.com/64260161/80511388-aa657980-8999-11ea-9ea8-df472ef25d07.png)

**Comment by Durgasish1o** [comment]
![2020-04-28 (3)](https://user-images.githubusercontent.com/64260161/80511787-34154700-899a-11ea-8c03-128b6bd7b88a.png)

**Comment by muhrahmatullah** [comment]
https://stackoverflow.com/questions/37424544/firebase-database-permission-denied-with-read-write-permissions-set-to-true

**Comment by Durgasish1o** [comment]
Sir just one question please tell me after you created and enabled dialogflow have you edited the inlinefulfillment or added anything to your data base .. Please sir tell the steps

**Comment by Durgasish1o** [comment]
Sir thank u I got it thanks a lot sir thanks a lot if you had not been there I might not be able to to it sir thanks a ton again and again
